export const SET_ALERTS = 'SET-ALERTS';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const INIT_SOCKET = 'INIT_SOCKET';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const UPDATE_USER = 'UPDATE_USER';

export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';
export const ACTIVE_CHANGED = 'ACTIVE_CHANGED';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const ACTIVITY_ADDED = 'ACTIVITY_ADDED';
export const EDIT_ACTIVITY = 'EDIT_ACTIVITY';
export const ACTIVITY_EDITED = 'ACTIVITY_EDITED';
