export const SET_ALERTS = 'SET-ALERTS';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const INIT_SOCKET = 'INIT_SOCKET';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const UPDATE_USER = 'UPDATE_USER';

export const START_HANDLING_REQUEST = 'START_HANDLING_REQUEST';
export const REQUEST_HANDLED = 'REQUEST_HANDLED';
